# Generated by Django 2.0 on 2020-08-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blong', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='f_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicacion'),
        ),
    ]
