# Generated by Django 2.1 on 2020-10-02 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blong', '0002_auto_20200827_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publicacion',
            options={'ordering': ['-f_pub'], 'verbose_name': 'Publicacion', 'verbose_name_plural': 'Publicaciones'},
        ),
    ]
